apiVersion: v1
kind: Secret
metadata:
  name: filestore-backup
type: Opaque
data:
  gcp_gcloud_auth: <Base64 encoded Service Account Key>
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: filestore-backup
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: filestore-backup
            image: <Image URL>
            imagePullPolicy: Always
            env:
              - name: GCP_GCLOUD_AUTH
                valueFrom:
                   secretKeyRef:
                     name: filestore-backup
                     key: gcp_gcloud_auth
              - name: BACKUP_PROVIDER
                value: "gcp"
              - name: GCP_BUCKET_NAME
                value: "<Your GCS Bucket Name>"
              - name: FILESHARE_MOUNT_PRIMARY
                value: "<local path for primary filestore mount>"
              - name: FILESTORE_IP_PRIMARY
                value: "<IP address of primary filestore>"
              - name: FILESHARE_NAME_PRIMARY
                value: "<fileshare name of primary filestore>"
              - name: FILESHARE_MOUNT_SECONDARY
                value: "local path for secondary filestore mount>"
              - name: FILESTORE_IP_SECONDARY
                value: "<IP address of secondary filestore>"
              - name: FILESHARE_NAME_SECONDARY
                value: "fileshare name of secondary filestore>"             
          restartPolicy: Never
